[package]
name = "cryo_cooler_controller_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "*"
crc = "*"
bitflags = "2.0.0-rc.1"
chrono = "0.4"
